# Generated by Django 5.1.5 on 2025-03-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('capacidade', models.IntegerField()),
                ('responsavel', models.CharField(max_length=255)),
                ('periodo', models.CharField(choices=[('M', 'Matutino'), ('T', 'Vespertino'), ('N', 'Noturno'), ('S', 'Integral')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('tipo_curso', models.CharField(choices=[('CI', 'Curso técnico'), ('CAI', 'Curso Aprendizagem Industrial'), ('CS', 'Curso Superior'), ('CI', 'Curso técnico'), ('CI', 'Curso técnico')], max_length=5)),
                ('horas_aula', models.FloatField()),
                ('sigla', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('turma', models.CharField(max_length=255)),
            ],
        ),
    ]
