# Generated by Django 5.1.5 on 2025-03-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ambiente_curso_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_curso',
            field=models.CharField(choices=[('CI', 'Curso técnico'), ('CAI', 'Curso Aprendizagem Industrial'), ('CS', 'Curso Superior'), ('FIC', 'Formação Inicial e Continuada')], max_length=5),
        ),
    ]
